# Generated by Django 3.2.9 on 2021-11-21 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_editorjs.fields
import journalApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_image', models.ImageField(blank=True, default='uploads/onecki.jpg', null=True, upload_to=journalApp.models.upload_to, verbose_name='Image')),
                ('unique_id', models.CharField(editable=False, max_length=100, null=True)),
                ('article_title', models.CharField(max_length=250, null=True, verbose_name='Title')),
                ('article_content', django_editorjs.fields.EditorJsField(null=True, verbose_name='Content')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author_of_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_of_article', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_comment_content', models.TextField(max_length=1000, null=True, verbose_name='Comment')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_article', to='journalApp.article_journal', verbose_name='Article')),
                ('article_comment_user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_article', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_image', models.ImageField(blank=True, default='uploads/onecki.jpg', null=True, upload_to=journalApp.models.upload_to, verbose_name='Cover photo')),
                ('unique_id', models.CharField(editable=False, max_length=100, null=True)),
                ('journal_name', models.CharField(max_length=250, null=True, verbose_name='Journal Name')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('requesting_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Close')], default='closed', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Journal_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Journal Category')),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestAuthorShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Request'), ('accepted', 'Accept'), ('rejected', 'Reject'), ('banned', 'Request Exceeded'), ('blocked', 'Blocked'), ('created', 'Created')], default='requested', max_length=50)),
                ('member_status', models.CharField(choices=[('founder', 'Founder'), ('admin', 'Admin'), ('author', 'Author'), ('any', 'Any')], default='author', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journalApp.journal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_seen', models.BooleanField(default=False)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='journalApp.article_journal')),
                ('first_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='journalApp.comment')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='journalApp.journal')),
                ('second_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='journalApp.comment')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Journal_Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Issue Name')),
                ('year', models.IntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='Year')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journalApp.journal', verbose_name='Journal')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_of_journal', to='journalApp.journal_category', verbose_name='Journal Category'),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journal_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FollowerJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journalfollow', to='journalApp.journal')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journalfollow', to=settings.AUTH_USER_MODEL, verbose_name='Follower')),
            ],
            options={
                'verbose_name_plural': 'Journal Subscription',
            },
        ),
        migrations.CreateModel(
            name='FavoriteArticleJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_article_journal', to='journalApp.article_journal')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_article_journal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.AddField(
            model_name='article_journal',
            name='issue_name_of_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_name_of_article', to='journalApp.journal_issue', verbose_name='Select the Issue'),
        ),
        migrations.AddField(
            model_name='article_journal',
            name='journal_name_of_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_name_of_article', to='journalApp.journal', verbose_name='Select the Journal'),
        ),
    ]
